import React from 'react';

interface Props {
  onClose: () => void;
  isOpen?: boolean; // Optional to prevent TS errors in other games
  serverSeed?: string;
  serverSeedHash?: string;
}

export default function ProvablyFairModal({ onClose, isOpen, serverSeed, serverSeedHash }: Props) {
  // If explicitly passed false from games managing their own open state, hide it.
  if (isOpen === false) return null;

  return (
    <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-fade-in">
      <div className="bg-[#0a0f0c] border border-green-500 max-w-2xl w-full rounded-xl p-8 shadow-[0_0_50px_rgba(34,197,94,0.2)]">
        <h2 className="text-3xl font-black text-white uppercase tracking-tighter mb-4 flex items-center justify-between">
          🛡️ Provably Fair <button onClick={onClose} className="text-gray-500 hover:text-white">✕</button>
        </h2>
        <p className="text-gray-400 mb-6 leading-relaxed">
          We operate on the <strong className="text-white">"Check it yourself"</strong> principle. Outcomes are determined by a cryptographic commit-reveal scheme mathematically verified by the Solana smart contract.
        </p>
        
        <div className="bg-black border border-green-900/50 p-4 rounded font-mono text-sm text-green-400 mb-6 flex flex-col gap-3 break-all">
          <div>
            <span className="text-gray-500 text-xs uppercase tracking-widest block mb-1">Target Hash</span>
            {serverSeedHash || "HMAC-SHA256(Server Seed + Client Seed)"}
          </div>
          <div>
            <span className="text-gray-500 text-xs uppercase tracking-widest block mb-1">Revealed Server Seed</span>
            {serverSeed || "Hidden until round completes"}
          </div>
        </div>

        <ul className="space-y-4 text-sm text-gray-300">
          <li><strong className="text-white">1. Server Seed:</strong> Generated by the House and hashed before you bet. You verify this hash later.</li>
          <li><strong className="text-white">2. Client Seed:</strong> Generated by your browser to ensure the House cannot pre-calculate the result.</li>
          <li><strong className="text-white">3. Smart Contract Resolution:</strong> The House reveals the raw Server Seed. The Rust contract proves it matches the original hash, combined with your seed, placing the results verifiably.</li>
        </ul>
      </div>
    </div>
  );
}